<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lessons')->insert([
            [
                'course_id' => 1,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 1,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 1,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 1,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 2,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 2,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 2,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 2,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 3,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 3,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 3,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 3,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 4,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 4,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 4,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 4,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 5,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 5,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 5,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 5,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 6,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 6,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 6,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 6,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 7,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 7,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 7,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 7,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 8,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 8,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 8,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 8,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 9,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 9,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 9,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 9,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 10,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 10,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 10,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 10,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 11,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 11,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 11,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 11,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 12,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 12,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 12,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 12,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 13,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 13,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 13,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 13,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 14,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 14,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 14,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 14,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 15,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 15,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 15,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 15,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 16,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 16,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 16,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 16,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 17,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 17,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 17,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 17,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 18,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 18,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 18,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 18,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 19,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 19,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 19,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 19,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 20,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 20,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 20,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 20,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 21,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 21,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 21,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 21,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 22,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 22,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 2,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 22,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 23,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 23,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 23,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 23,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 24,
                'lesson_title' => 'Bab 1',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 24,
                'lesson_title' => 'Bab 2',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 24,
                'lesson_title' => 'Bab 3',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
            [
                'course_id' => 24,
                'lesson_title' => 'Bab 4',
                'created_at' => 'now',
                'updated_at' => 'now',
            ],
        ]);
    }
}
